# Generated by Django 4.1.7 on 2023-04-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='publicoffice',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
