# Generated by Django 4.1.7 on 2023-04-14 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_field_description_alter_field_field_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='form_belong_to',
            new_name='form_id',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='office_belong_to',
            new_name='office_id',
        ),
    ]
