# Generated by Django 4.1.7 on 2023-04-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_form_belong_to_field_form_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicoffice',
            name='name',
            field=models.CharField(default='', max_length=50, null=True, unique=True),
        ),
    ]
